name: neo_cat_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  equatable: ^2.0.5
  file_picker: ^5.5.0
  fluent_ui: ^4.7.5
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.2
  graphview: ^1.2.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
