name: neo_cat_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.2
  dio: ^5.3.3
  equatable: ^2.0.5
  extended_text: ^11.1.0
  extended_text_field: ^12.1.0
  file_picker: ^5.5.0
  fluent_ui: ^4.7.5
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_gen: ^5.3.2
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  graphview: ^1.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  msix: ^3.16.6
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter_gen:
  output: lib/gen/
  line_length: 80

msix_config:
  display_name: neo_cat_flutter
  msix_version: 1.0.0.0
  

flutter:
  uses-material-design: true
  fonts:
    - family: NeoCat
      fonts:
        - asset: assets/fonts/SourceHanSansCN-Bold.otf
        - asset: assets/fonts/SourceHanSansCN-Normal.otf